### ISSUE TITLE
Bug sur la récupération

### ISSUE THREAD

**Issue by ludogomez** [gtranche/jeedom-trafic-transilien#2]
Bonjour @gtranche 

depuis debut novembre 2016, le plugin ne marche plus.
En cherchant un peu, j'ai trouvé le problème. Vous utilisez une majuscule pour le nom de la ligne alors que le flux RSS veut une minuscule.

Il suffit de modifier le fichier php de la configuration du plugin et de renommer tous les logos en minuscule.

J'ai fait la modif à la main sur mon jeedom et c'est opérationnel.

Merci
Cordialement,

**Comment by gtranche** [comment]
Merci, je n'avais pas vu le problème vu que les incidents remontaient bien sur une ligne de ter ...
Pourtant pas d'incidents sur le RER A j'aurais du me douter de quelque chose !
Je repush sur le dépôt de jeedom au plus vite.

**Comment by ludogomez** [comment]
Cool, merci. J'attends la mise à jour sur jeedom pour remettre d'équerre les fichiers.
J'avais fait le bourrin en renommant tous les fichiers. Votre solution est plus élégante (strtolower)

@+

**Comment by ludogomez** [comment]
Bonjour,

est il possible d'ajouter la date de publication de l'alerte dans le plugin, c'est le tag pubDate dans le flux RSS ?

Merci

@+

30 janvier 2017 10:33 "gtranche"  a écrit:
	Merci, je n'avais pas vu le problème vu que les incidents remontaient bien sur une ligne de ter ...
Pourtant pas d'incidents sur le RER A j'aurais du me douter de quelque chose !
Je repush sur le dépôt de jeedom au plus vite.
