### ISSUE TITLE
Plugin introuvable : /var/www/html/core/class/../../plugins/trafictransilien/plugin_info/info.json

### ISSUE THREAD

**Issue by laserplouf** [gtranche/jeedom-trafic-transilien#3]
Plugin introuvable : /var/www/html/core/class/../../plugins/trafictransilien/plugin_info/info.json

Hom to complently suppress plug-in

**Comment by gtranche** [comment]
Le plugin a été supprimé manuellement ?
normalement il suffit de le virer depuis le market.
Je n'ai pas spécialement eu le temps de mettre à jour le plugin depuis un petit temps ...

**Comment by laserplouf** [comment]
Bonjour,

Merci pour la réponse rapide, je comprend bien les problèmes de temps et de
priorité.

Le plugin n'a pas été supprimé manuellement mais via Jeedom
Je suis en V3 et le plugin est obsolète donc pas réinstallable.
Probablement un complément de nettoyage à faire à la main.
Ecriture dans les log mais pas d'impact pénalisant.

Xavier



Xavier Bonnin

2017-10-23 15:11 GMT+02:00 Gtranche <notifications@github.com>:

**Comment by gtranche** [comment]
à priori je dois supprimer moi même le répertoire  /usr/share/nginx/www/jeedom/plugins/nom du plugin
à la suppression du plugin. Je vais essayer de corriger le plugin rapidement pour avoir une version "non obsolète" sur le site

**Comment by laserplouf** [comment]
OK, super.
Bon courage



Xavier Bonnin

**Comment by gtranche** [comment]
oh  !
je me souviens,
en fait dans la suppression du plugin je ne supprime pas le cron qui est créé pour que le plugin fonctionne.
Je vais maj le plugin, mais déjà pour virer les logs, vas dans la configuration et le moteur de taches.
Tu dois avoir une ligne avec la classe plugin et cron en "* * * * *" le problème c'est de savoir lequel est le bon ...

**Comment by gtranche** [comment]
Normalement c'est poussé sur le market, le temps que ce soit validé.

**Comment by jordanderoubaix** [comment]
Bonjour !
Pour info, la mise à jour depuis le market ne peut pas se faire (mais en récupérant les sources du GIT et les poussant manuellement l'erreur du json est bien corrigée).

**Comment by gtranche** [comment]
oui, je n'avais pas compris pourquoi il était obsolète, j'ai envoyé le patch normalement le temps que la moulinette passe chez eux.

**Comment by laserplouf** [comment]
Je suis en pleine rénovation d'une salle de bain.
Peu de temps dispo pour jouer sur GitHub, mais ce serait un plaisir
d'essayer de faire et mettre à disposition un plugin comme tu l'a fait.
Merci pour tes actions

Xavier.



Xavier Bonnin

2017-11-02 10:57 GMT+01:00 Gtranche <notifications@github.com>:

**Comment by gtranche** [comment]
Problème réglé avec la dernière release
