### ISSUE TITLE
desktop/php/trafictransilien.php

### ISSUE THREAD

**Issue by aladin2000** [gtranche/jeedom-trafic-transilien#4]
bonjour , j'ai un petit probleme avec l'affichage de ton plugin 
1°) impossible de faire apparaître deux lignes par exemple la rer A et la ligne J sur le dashboard

2°) en plus je voulais te faire part d"une anomalier de tabulation dans le code  desktop/php/trafictransilien.php
La ligne 97 semble par respectée  ou alors, l'effet de refraischissemernt ne permet pas à la première vue de voir la loiste des options de nom de ligne ( il faut faire un deuxième refresh du browser) peut etre la cause... est ailleurs

3°) sur le titre principal, apprait une icône avec un triangle , est ce normal ?

Merci pour ton aide par avance

**Comment by gtranche** [comment]
Effectivement je viens de voir qu'on ne peut pas choisir la ligne depuis les dernière mise à jour de jeedom.
C'est aussi pour cela que tu ne peux pas afficher 2 lignes, vu que du coup pour lui il s'agit de la même.

Je corrige ça au plus vite.

**Comment by gtranche** [comment]
C'est corrigé, je suis un boulet ... j'ai foutu un / a la fin de la ligne du select (du coup en xml il ne prend pas de balise de sortie) ....
bref normalement le problème que tu avais avec le multi ligne devrait être réglé, je push le contenu sur jeedom.
