### ISSUE TITLE
multilignes 

### ISSUE THREAD

**Issue by aladin2000** [gtranche/jeedom-trafic-transilien#5]
Dsl de t'importuner 
de nouveau le soucis multilignes du plugin. Il me semble que malgré le premier correctif , il subsiste tjs
un problème  car le ne parviens pas à rendre 'visibles' les tuiles attachées à un objet père.
Les commandes fonvctionnent pourtant mais le graphique reste invisible et a meme disparu depuis la dernière version.
j'ai  tout essayé les ctrl F5 et reboot de l'instance . J'ai même essayé avec une autre instance Jeedom (preprod et prod )
mais rien n'y fait . 
Le probleme est peut être dans jeedom, quoique je ne rencontre aucun autre problème de tuiles qui disparaissent mis à pas  celle de ton plugin.

**Comment by gtranche** [comment]
Pas de soucis.
Alors par contre j'ai du mal à comprendre où se situe le problème. J'ai 2 lignes en même temps sur le mien ..
Je pensais que ça venait du problème de sélection, dans mes souvenirs j'avais lié le nom de la ligne au widget. Du coup si ton widget n'avait pas de ligne associée il ne voulait pas ajouter un 2ème widget avec le même nom.
J'essaye d'installer un jeedom cette semaine pour tester et corriger.

**Comment by gtranche** [comment]
Bon !
du coup effectivement y'a une merde !
j'ai fait 2/3 correctifs, par exemple la ligne sélectionnée et enregistrée n'était plus affichée quand on revenait dans la configuration.
Par contre impossible de corriger le problème de base automatiquement.
La bonne nouvelle c'est que temporairement je peux te proposer un workaround, après avoir perdu ce qui me restait de cheveux j'ai trouvé le soucis.
En gros tu vas dans ton widget que tu as config, tu cliques sur les rouages en haut a droite (sous l'heure) et il faut activer "visible". Il faut que je trouve comment on l'active par defaut.
En fait je me demande si je ne vais pas ajouter le "isvisible" dans la conf comme pour le isenable.

Je garde le ticket pour corriger ça.

**Comment by gtranche** [comment]
bon en fait j'ai ajouté le visible, et ça fonctionne.
Je push !
